// Country name to ISO 3166-1 alpha-2 code mapping for Spotify API
export const COUNTRY_CODE_MAP: { [key: string]: string } = {
  // North America
  "United States": "US",
  "United States of America": "US",
  "Canada": "CA",
  "Mexico": "MX",

  // Central America & Caribbean
  "Belize": "BZ",
  "Costa Rica": "CR",
  "El Salvador": "SV",
  "Guatemala": "GT",
  "Honduras": "HN",
  "Nicaragua": "NI",
  "Panama": "PA",
  "Antigua and Barbuda": "AG",
  "Bahamas": "BS",
  "Barbados": "BB",
  "Cuba": "CU",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Grenada": "GD",
  "Haiti": "HT",
  "Jamaica": "JM",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Trinidad and Tobago": "TT",

  // South America
  "Argentina": "AR",
  "Bolivia": "BO",
  "Brazil": "BR",
  "Chile": "CL",
  "Colombia": "CO",
  "Ecuador": "EC",
  "Guyana": "GY",
  "Paraguay": "PY",
  "Peru": "PE",
  "Suriname": "SR",
  "Uruguay": "UY",
  "Venezuela": "VE",

  // Western Europe
  "Austria": "AT",
  "Belgium": "BE",
  "France": "FR",
  "Germany": "DE",
  "Ireland": "IE",
  "Italy": "IT",
  "Luxembourg": "LU",
  "Malta": "MT",
  "Netherlands": "NL",
  "Portugal": "PT",
  "Spain": "ES",
  "Switzerland": "CH",
  "United Kingdom": "GB",
  "England": "GB",
  "Scotland": "GB",
  "Wales": "GB",
  "Northern Ireland": "GB",

  // Northern Europe
  "Denmark": "DK",
  "Estonia": "EE",
  "Finland": "FI",
  "Iceland": "IS",
  "Latvia": "LV",
  "Lithuania": "LT",
  "Norway": "NO",
  "Sweden": "SE",

  // Southern Europe
  "Albania": "AL",
  "Bosnia and Herzegovina": "BA",
  "Bulgaria": "BG",
  "Croatia": "HR",
  "Cyprus": "CY",
  "Greece": "GR",
  "Macedonia": "MK",
  "North Macedonia": "MK",
  "Montenegro": "ME",
  "Romania": "RO",
  "Serbia": "RS",
  "Slovenia": "SI",

  // Eastern Europe
  "Belarus": "BY",
  "Moldova": "MD",
  "Russia": "RU",
  "Ukraine": "UA",

  // Central & Western Asia
  "Armenia": "AM",
  "Azerbaijan": "AZ",
  "Georgia": "GE",
  "Kazakhstan": "KZ",
  "Kyrgyzstan": "KG",
  "Tajikistan": "TJ",
  "Turkmenistan": "TM",
  "Uzbekistan": "UZ",

  // Middle East & North Africa
  "Afghanistan": "AF",
  "Bahrain": "BH",
  "Egypt": "EG",
  "Iran": "IR",
  "Iraq": "IQ",
  "Israel": "IL",
  "Jordan": "JO",
  "Kuwait": "KW",
  "Lebanon": "LB",
  "Libya": "LY",
  "Morocco": "MA",
  "Oman": "OM",
  "Palestine": "PS",
  "Palestinian Territories": "PS",
  "Qatar": "QA",
  "Saudi Arabia": "SA",
  "Syria": "SY",
  "Tunisia": "TN",
  "Turkey": "TR",
  "United Arab Emirates": "AE",
  "Yemen": "YE",

  // South Asia
  "Bangladesh": "BD",
  "Bhutan": "BT",
  "India": "IN",
  "Maldives": "MV",
  "Nepal": "NP",
  "Pakistan": "PK",
  "Sri Lanka": "LK",

  // Southeast Asia
  "Brunei": "BN",
  "Cambodia": "KH",
  "Indonesia": "ID",
  "Laos": "LA",
  "Malaysia": "MY",
  "Myanmar": "MM",
  "Burma": "MM",
  "Philippines": "PH",
  "Singapore": "SG",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "East Timor": "TL",
  "Vietnam": "VN",

  // East Asia
  "China": "CN",
  "Hong Kong": "HK",
  "Japan": "JP",
  "Mongolia": "MN",
  "North Korea": "KP",
  "South Korea": "KR",
  "Korea": "KR",
  "Taiwan": "TW",

  // Oceania
  "Australia": "AU",
  "Fiji": "FJ",
  "Kiribati": "KI",
  "Marshall Islands": "MH",
  "Micronesia": "FM",
  "Nauru": "NR",
  "New Zealand": "NZ",
  "Palau": "PW",
  "Papua New Guinea": "PG",
  "Samoa": "WS",
  "Solomon Islands": "SB",
  "Tonga": "TO",
  "Tuvalu": "TV",
  "Vanuatu": "VU",

  // Sub-Saharan Africa
  "Angola": "AO",
  "Benin": "BJ",
  "Botswana": "BW",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cameroon": "CM",
  "Cape Verde": "CV",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Comoros": "KM",
  "Congo": "CG",
  "Democratic Republic of the Congo": "CD",
  "Congo-Kinshasa": "CD",
  "Côte d'Ivoire": "CI",
  "Ivory Coast": "CI",
  "Djibouti": "DJ",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Ethiopia": "ET",
  "Gabon": "GA",
  "Gambia": "GM",
  "Ghana": "GH",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Kenya": "KE",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Mali": "ML",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mozambique": "MZ",
  "Namibia": "NA",
  "Niger": "NE",
  "Nigeria": "NG",
  "Rwanda": "RW",
  "São Tomé and Príncipe": "ST",
  "Senegal": "SN",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Sudan": "SS",
  "Sudan": "SD",
  "Swaziland": "SZ",
  "Eswatini": "SZ",
  "Tanzania": "TZ",
  "Togo": "TG",
  "Uganda": "UG",
  "Zambia": "ZM",
  "Zimbabwe": "ZW",

  // Additional territories and special cases
  "American Samoa": "AS",
  "Aruba": "AW",
  "Bermuda": "BM",
  "British Indian Ocean Territory": "IO",
  "Cayman Islands": "KY",
  "Curacao": "CW",
  "Falkland Islands": "FK",
  "Faroe Islands": "FO",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  "Gibraltar": "GI",
  "Greenland": "GL",
  "Guadeloupe": "GP",
  "Guam": "GU",
  "Guernsey": "GG",
  "Isle of Man": "IM",
  "Jersey": "JE",
  "Martinique": "MQ",
  "Mayotte": "YT",
  "Montserrat": "MS",
  "Netherlands Antilles": "AN",
  "New Caledonia": "NC",
  "Niue": "NU",
  "Norfolk Island": "NF",
  "Northern Mariana Islands": "MP",
  "Puerto Rico": "PR",
  "Réunion": "RE",
  "Saint Barthélemy": "BL",
  "Saint Helena": "SH",
  "Saint Martin": "MF",
  "Saint Pierre and Miquelon": "PM",
  "Sint Maarten": "SX",
  "Svalbard and Jan Mayen": "SJ",
  "Turks and Caicos Islands": "TC",
  "United States Minor Outlying Islands": "UM",
  "British Virgin Islands": "VG",
  "Virgin Islands": "VI",
  "US Virgin Islands": "VI",
  "Wallis and Futuna": "WF",
  "Western Sahara": "EH",
};
